site_name: Misskey.fr
nav:
    - Accueil: index.md
    - Commencer avec Missskey:
      - "Créer un compte":  getting-started/créer-un-compte.md
      - "Configurer son compte": getting-started/configurer-son-compte.md
      - "Les notes": getting-started/les-notes.md
    - Guide avancé:
        - "Les Listes & Antennes": guide-avance/les-listes-et antennes.md
        - "Synthax MFM": guide-avance/synthax-mfm.md
    - Personnalisation de Misskey:
        - "Les thèmes": personnalisation/thème.md
        - "CSS avec Stylus": personnalisation/css-stylus.md
theme: 
  name: 'material'
  palette:
    primary: 'green'
    scheme: 'slate'
    accent: 'green'
  features:
    - navigation.tabs
  font: false
  language: fr
  icon:
    repo: fontawesome/brands/github-alt

repo_url: https://github.com/kazukyakayashi/wiki-misskey
repo_name: Github Wiki Misskey

markdown_extensions:
  - footnotes
  - admonition
  - attr_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra:
  search:
    language: 'fr, en'
plugins:
  - search
site_description: "Wiki francophone sur le fonctionnement du réseau social Misskey"
site_author: "KazukyAkayashi"
copyright: "Contenu sous GNU Free Documentation License, Servez vous !! 🎉"

extra_css:
  - stylesheets/extra.css
